security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Tecnotek\ExpedienteBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        db_users:
            entity: { class: TecnotekExpedienteBundle:User }
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                superadminm: { password: abc123, roles: [ 'ROLE_SUPERADMIN' ] }
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #login:
        #    pattern:  ^/expediente/secured/login$
        #    security: false
        main:
            pattern:      .*
            form-login:
                login_path:     /expediente/secured/login
                use_forward:    false
                check_path:     /expediente/secured/login_check
                failure_path:   null
                default_target_path:  /expediente/
                always_use_default_target_path: true
            logout:       
                path:   /expediente/secured/logout
                target: /expediente/
            anonymous:    true
            
        secured_area:
            pattern:    ^/expediente/secured/
            form_login:
                check_path: /expediente/secured/login_check
                login_path: /expediente/secured/login
                default_target_path:  /expediente/
                always_use_default_target_path: true
            logout:
                path:   /expediente/secured/logout
                target: /expediente/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: /expediente/secured/login.*, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/expediente.*, role: IS_AUTHENTICATED_FULLY  }
        
        #- { path: ^/expediente/sysadmin.*, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
